(provide 'smarty-macros)
(defun comment-stuff-comment (start end) (goto-char start)
       (insert "{*")
       (goto-char (+ 1 end))
       (insert "*}")
       )
(defun comment-stuff-uncomment (start end buffer-substring)
  (goto-char (+ start (cl-search "{*" buffer-substring)))
  (delete-char 2)
  (goto-char (+ start (cl-search "*}" buffer-substring) -2))
  (delete-char 2)
  )
(defun comment-stuff (start end)
  (interactive "r")
  (if (cl-search "{*" (buffer-substring-no-properties start end))
      (comment-stuff-uncomment start end (buffer-substring-no-properties start end))
    (comment-stuff-comment start end)
    )
  )

(spacemacs/declare-prefix-for-mode 'web-mode "mc" "comment")
(spacemacs/set-leader-keys-for-major-mode 'web-mode "cc" 'comment-stuff)
